### ISSUE TITLE
Pytorch GPU on windows 10 error: Windows not yet supported for torch.compile

### ISSUE THREAD

**Issue by quitmeyer** [Imageomics/pybioclip#26] opened 2024-08-13 12:22 UTC
Apparently, There's a known issue with Windows where it can't use torch.compile, But usually you can override this with a flag When the script is run and it will just use CPU stuff and be slower. 

But it looks like the call torch.compile is embedded in the code directly and so it seems that if you have Windows and are trying to run this it might not be possible to run it? 

Because you will keep getting this error 
"Pytorch GPU on windows 10 error: Windows not yet supported for torch.compile"

**Comment by hlapp** [comment] 2024-08-13 13:15
@quitmeyer do you have a link for how/where the flag is applied?

**Comment by hlapp** [comment] 2024-08-13 13:39
According to pytorch/pytorch#122094 this is a compile time (for the PyTorch library) not a runtime (of a Python script) issue, and it doesn't seem specific to whether the CPU or GPU device is used. So it's not clear there's anything we can do here.

**Comment by Choco31415** [comment] 2024-08-13 13:54
@hlapp The flag is --compile=False

It looks like the issue is with torch.compile()'s dependency on Triton which can be seen [here](https://github.com/pytorch/pytorch/issues/90768#issuecomment-1449712675).

The good news is that PyTorch nightly now supports torch.compile() on Windows. More details can be seen [here](https://github.com/pytorch/pytorch/issues/122094#issuecomment-2267105089). We tested the fix and it works without issue.

**Comment by hlapp** [comment] 2024-08-13 14:12
> @hlapp The flag is --compile=False

Yes, but that's a compile time flag (for compiling the Torch libraries, not for calling `pytorch.compile()`).

**Comment by quitmeyer** [comment] 2024-08-13 15:06
I successfully got mine running on Windows by uninstalling pytorch and then installing the nightly build suggested above

**Comment by hlapp** [comment] 2024-08-14 01:42
Looks like (a) this is an issue with PyTorch, not pybioclip, and (b) it can be remedied for now by uninstalling PyTorch and installing the nightly build instead.

Presumably, once the changes in PyTorch have made it into a release, this problem should go away. Closing for now.

**Closed by hlapp** 2024-08-14 01:42 UTC
